/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-02-02

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"
#include "UART.h"
#include <stdio.h>
#include <stdlib.h>

// Global variables to store the frequency of the square signal
#define TIMCLOCK 26880000
#define PRESCALAR 26
uint32_t IC_Val1 = 0;
uint32_t IC_Val2 = 0;
uint32_t Difference = 0;
int Is_First_Captured = 0;
float frequency = 0;


#define ARRAY_SIZE 300
int buffer[ARRAY_SIZE];
int i = 0;



// Function to configure the GPIOA pin6
void configureGPIOA6(void)
{
	// Enable clock for GPIOA
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	// Configure PA6 as alternate function
	GPIOA->MODER &= ~GPIO_MODER_MODER6;
	GPIOA->MODER |= GPIO_MODER_MODER6_1;
	GPIOA->AFR[0] |= 0x2 << 24;
}

// Function to configure the timer
void TIM3_IC_Init(void)
{
	// Enable clock for TIM3
	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;

	// Configure TIM3 in input capture mode
	TIM3->CCMR1 &= ~TIM_CCMR1_CC1S;
	TIM3->CCMR1 |= TIM_CCMR1_CC1S_0;
	TIM3->CCER &= ~TIM_CCER_CC1P;
	TIM3->CCER |= TIM_CCER_CC1E;
	TIM3->CCMR1 &= ~(BIT7 | BIT5 | BIT4);
	TIM3->CCMR1 |= (BIT6);
	TIM3->CCMR1 &= ~TIM_CCMR1_IC1F;
	TIM3->PSC = 26 - 1;
	TIM3->DIER |= TIM_DIER_CC1IE;

	// Enable TIM3 global interrupt
	NVIC_EnableIRQ(TIM3_IRQn);

	// Start TIM3
	TIM3->CR1 |= TIM_CR1_CEN;
}


void TIM3_IRQHandler(void)
{

  if (TIM3->SR & TIM_SR_CC1IF)
  {
	  if(Is_First_Captured == 0){
		  IC_Val1 = TIM3->CCR1;
		  Is_First_Captured = 1;
	  }
	  else{
		  IC_Val2 = TIM3->CCR1;
		  if(IC_Val2 > IC_Val1){
			  Difference = IC_Val2 - IC_Val1;
		  }
		  else if(IC_Val1 > IC_Val2){
			  Difference = (0xFFFF - IC_Val1) + IC_Val2;

		  }
		  float refClock = TIMCLOCK /(PRESCALAR);
		  frequency = refClock/Difference;
		  buffer[i++] = frequency;
		  while(i > ARRAY_SIZE);
		  TIM3->SR &= ~TIM_SR_CC1IF;
		  Is_First_Captured = 0;
	  }
  }
}


int main(void)
{

  // Configure the GPIO pin
  configureGPIOA6();

  // Configure the timer
  TIM3_IC_Init();

  configureUART();

  while (1){
	  TIM3->CCR4 = 50;
  }
}

