/*
 * imput_capture_config.c
 *
 *  Created on: Feb 21, 2023
 *      Author: ousmane
 */
#include "input_capture_config.h"
#include "macros_utiles.h"

void TIM5_CH1_IC_Init(){

	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	TIM5->CCMR1 &= ~TIM_CCMR1_CC1S;
	TIM5->CCMR1 |= TIM_CCMR1_CC1S_0;
	TIM5->CCER &= ~TIM_CCER_CC1P;
	TIM5->CCER |= TIM_CCER_CC1E;
	TIM5->CCMR1 &= ~(BIT7 | BIT5 | BIT4);
	TIM5->CCMR1 |= (BIT6);
	TIM5->PSC = 26 - 1;
	TIM5->DIER |= TIM_DIER_CC1IE;
	NVIC_EnableIRQ(TIM5_IRQn);
}


void configureGPIOA0(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER0;
	GPIOA->MODER |= GPIO_MODER_MODER0_1;
	GPIOA->AFR[0] |= (2 << 0);
}

void TIM5_CH2_IC_Init(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	TIM5->CCMR1 &= ~TIM_CCMR1_CC2S;
	TIM5->CCMR1 |= TIM_CCMR1_CC2S_0;
	TIM5->CCER &= ~TIM_CCER_CC2P;
	TIM5->CCER |= TIM_CCER_CC2E;
	TIM5->CCMR1 &= ~(BIT15 | BIT13 | BIT12);
	TIM5->CCMR1 |= (BIT14);
	TIM5->PSC = 26 - 1;
	TIM5->DIER |= TIM_DIER_CC2IE;
	NVIC_EnableIRQ(TIM5_IRQn);
}

void configureGPIOA1(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER1;
	GPIOA->MODER |= GPIO_MODER_MODER1_1;
	GPIOA->AFR[0] |= (2 << 4);
}


void TIM5_CH3_IC_Init(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	TIM5->CCMR2 &= ~TIM_CCMR2_CC3S;
	TIM5->CCMR2 |= TIM_CCMR2_CC3S_0;
	TIM5->CCER &= ~TIM_CCER_CC3P;
	TIM5->CCER |= TIM_CCER_CC3E;
	TIM5->CCMR2 &= ~(BIT7 | BIT5 | BIT4);
	TIM5->CCMR2 |= (BIT6);
	TIM5->PSC = 26 - 1;
	TIM5->DIER |= TIM_DIER_CC3IE;
	NVIC_EnableIRQ(TIM5_IRQn);
}

void configureGPIOA2(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER2;
	GPIOA->MODER |= GPIO_MODER_MODER2_1;
	GPIOA->AFR[0] |= (2 << 8);
}

void TIM5_CH4_IC_Init(){
	RCC->APB1ENR |= RCC_APB1ENR_TIM5EN;
	TIM5->CCMR2 &= ~TIM_CCMR2_CC4S;
	TIM5->CCMR2 |= TIM_CCMR2_CC4S_0;
	TIM5->CCER &= ~TIM_CCER_CC4P;
	TIM5->CCER |= TIM_CCER_CC4E;
	TIM5->CCMR2 &= ~(BIT15 | BIT13 | BIT12);
	TIM5->CCMR2 |= (BIT14);
	TIM5->PSC = 26 - 1;
	TIM5->DIER |= TIM_DIER_CC4IE;
	NVIC_EnableIRQ(TIM5_IRQn);
}
void configureGPIOA3(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~GPIO_MODER_MODER3;
	GPIOA->MODER |= GPIO_MODER_MODER3_1;
	GPIOA->AFR[0] |= (2 << 12);
}
